"""Branded export helpers for the weekly report (CSV / PDF / branded Excel)."""

from __future__ import annotations

import csv
import io
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Any, Iterable

from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.drawing.image import Image as XLImage
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


BRAND_NAME = "Gazebo HR"
BRAND_TAGLINE = "Weekly payroll & reporting"
PRIMARY_BLUE = "#003078"
ACCENT_BLUE = "#1d70b8"

EXPORT_COLUMNS = [
    "Name",
    "Category",
    "SageNo",
    "BasicHours",
    "MonFriOvertime",
    "SatSunOvertime",
    "AnnualHoliday",
    "TotalPaidHours",
    "ContractedHours",
    "Overtime",
]


def _now_label() -> str:
    return datetime.now().strftime("%d %B %Y, %H:%M")


def _logo_path() -> Path | None:
    here = Path(__file__).resolve().parent
    candidate = here / "static" / "images" / "logo.png"
    return candidate if candidate.exists() else None


def build_csv_bytes(rows: list[dict[str, Any]], summary: dict[str, Any] | None = None) -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([f"{BRAND_NAME} — Weekly report"])
    writer.writerow([f"Generated: {_now_label()}"])
    if summary:
        writer.writerow([
            f"Total rows: {summary.get('total_rows', '')}",
            f"Agency: {summary.get('agency_rows', '')}",
            f"Gazebo: {summary.get('gazebo_rows', '')}",
            f"Total paid hours: {summary.get('total_paid_hours', '')}",
        ])
    writer.writerow([])
    writer.writerow(EXPORT_COLUMNS)
    for r in rows:
        writer.writerow([r.get(c, "") for c in EXPORT_COLUMNS])
    return buf.getvalue().encode("utf-8-sig")


def add_branding_cover_sheet(xlsx_bytes: bytes, summary: dict[str, Any] | None = None) -> bytes:
    """Insert a branded cover sheet at index 0 of an existing xlsx workbook."""
    wb = load_workbook(BytesIO(xlsx_bytes))
    ws = wb.create_sheet(title="Cover", index=0)

    header_fill = PatternFill("solid", fgColor=PRIMARY_BLUE.lstrip("#"))
    title_font = Font(name="Calibri", size=22, bold=True, color="FFFFFF")
    sub_font = Font(name="Calibri", size=11, color="DDE3EE")
    label_font = Font(name="Calibri", size=11, bold=True, color="333333")
    value_font = Font(name="Calibri", size=11, color="333333")

    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 40

    ws.merge_cells("A1:B3")
    cell = ws["A1"]
    cell.value = f"{BRAND_NAME}\n{BRAND_TAGLINE}"
    cell.fill = header_fill
    cell.font = title_font
    cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True, indent=2)
    ws.row_dimensions[1].height = 26
    ws.row_dimensions[2].height = 26
    ws.row_dimensions[3].height = 26

    logo = _logo_path()
    if logo is not None:
        try:
            img = XLImage(str(logo))
            img.width = 110
            img.height = 34
            ws.add_image(img, "B1")
        except Exception:
            pass

    rows: list[tuple[str, str]] = [
        ("Report", "Weekly report"),
        ("Generated", _now_label()),
    ]
    if summary:
        rows.extend([
            ("Total rows", str(summary.get("total_rows", ""))),
            ("Agency rows", str(summary.get("agency_rows", ""))),
            ("Gazebo rows", str(summary.get("gazebo_rows", ""))),
            ("Total paid hours", str(summary.get("total_paid_hours", ""))),
        ])

    start_row = 5
    for offset, (label, value) in enumerate(rows):
        r = start_row + offset
        ws.cell(r, 1, label).font = label_font
        ws.cell(r, 2, value).font = value_font
        ws.cell(r, 1).alignment = Alignment(horizontal="left", vertical="center")
        ws.cell(r, 2).alignment = Alignment(horizontal="left", vertical="center")

    note_row = start_row + len(rows) + 2
    note = ws.cell(note_row, 1, f"This workbook was generated by {BRAND_NAME}.")
    note.font = Font(name="Calibri", size=9, italic=True, color="666666")
    ws.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=2)

    out = BytesIO()
    wb.save(out)
    return out.getvalue()


def build_pdf_bytes(rows: list[dict[str, Any]], summary: dict[str, Any] | None = None) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=landscape(A4),
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=14 * mm,
        title=f"{BRAND_NAME} — Weekly report",
        author=BRAND_NAME,
    )
    styles = getSampleStyleSheet()
    story: list[Any] = []

    logo = _logo_path()
    header_cells: list[Any] = []
    if logo is not None:
        try:
            header_cells.append(Image(str(logo), width=32 * mm, height=10 * mm))
        except Exception:
            header_cells.append("")
    else:
        header_cells.append("")
    header_cells.append(
        Paragraph(
            f"<font size=18 color='{PRIMARY_BLUE}'><b>{BRAND_NAME}</b></font><br/>"
            f"<font size=10 color='#555'>Weekly report — generated {_now_label()}</font>",
            styles["Normal"],
        ),
    )
    header = Table([header_cells], colWidths=[36 * mm, 230 * mm])
    header.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(header)

    if summary:
        meta = (
            f"<b>Total rows:</b> {summary.get('total_rows', '')}  "
            f"&nbsp;&nbsp;<b>Agency:</b> {summary.get('agency_rows', '')}  "
            f"&nbsp;&nbsp;<b>Gazebo:</b> {summary.get('gazebo_rows', '')}  "
            f"&nbsp;&nbsp;<b>Total paid hours:</b> {summary.get('total_paid_hours', '')}"
        )
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph(meta, styles["Normal"]))

    story.append(Spacer(1, 6 * mm))

    head = EXPORT_COLUMNS
    data: list[list[Any]] = [head]
    for r in rows:
        data.append([_pdf_cell(r.get(c, "")) for c in head])

    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(PRIMARY_BLUE)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ALIGN", (3, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (2, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 5),
        ("TOPPADDING", (0, 0), (-1, 0), 5),
    ]))
    story.append(table)

    def _draw_footer(canvas: Any, doc_obj: Any) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#666666"))
        footer = f"{BRAND_NAME} • Generated {_now_label()} • Page {doc_obj.page}"
        canvas.drawCentredString(doc_obj.pagesize[0] / 2.0, 8 * mm, footer)
        canvas.restoreState()

    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    return buf.getvalue()


def _pdf_cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value)


def export_filename(prefix: str, ext: str) -> str:
    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    return f"{prefix}_{stamp}.{ext}"
